#!/bin/bash
sudo apt update -y && sudo apt upgrade -y
sudo apt install -y python3-pip python3.11-venv
python3 -m venv airflow_venv
source airflow_venv/bin/activate
cd ./data_eng_airflow_etl
sudo chmod +x setup.sh
pip3 install -r requirements.txt